apiVersion: 1
datasources:
  - name: rad-tests-app
    type: frser-sqlite-datasource
    access: proxy
    orgId: 1
    isDefault: true
    jsonData:
      path: /var/lib/grafana/data/rad-tests-app.sqlite3
